### ISSUE TITLE
Element displacement when parent has transform propery

### ISSUE THREAD

**Issue by sikhaman** [dnd-kit/docs#39]
Hello folks I faced with a problem when element losing its correct position if its parent has a `transform` property

I created [codesandbox](https://codesandbox.io/p/sandbox/dnd-check-85sghx?file=%2Fsrc%2FApp.js%3A46%2C34) to show what I mean. Here I kinda simulating that my list can be in a popup that is floating and in positionig styles uses `transform` property. For example in my real app I use [floating-ui](https://floating-ui.com/docs/useFloating) hook to place my popup and its kinda ruining the styles of dnd.

Any ideas here what to do? I tried to create custom modifiers, but can not catch or check parents styles.

**Comment by LazyChun** [comment]
how do you fix it?
